name: esa_ltc25
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas==1.1.1
  - matplotlib==3.10.6
  - matplotlib-inline==0.1.7
  - netCDF4==1.7.2
  - numpy==2.2.6
  - pandas==2.3.2
  - rasterio==1.4.3
  - regionmask==0.13.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
  - seaborn==0.13.2
  - shap==0.48.0
  - xarray==2025.6.1
  - xgboost==3.0.5
  - jupyterlab>=4.0
  - ipykernel>=6.29
  - notebook>=7.0
  - pip:
      - numpy-groupies==0.11.3

